/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WebinarFirstComponent {
        "name": string;
    }
}
declare global {
    interface HTMLWebinarFirstComponentElement extends Components.WebinarFirstComponent, HTMLStencilElement {
    }
    var HTMLWebinarFirstComponentElement: {
        prototype: HTMLWebinarFirstComponentElement;
        new (): HTMLWebinarFirstComponentElement;
    };
    interface HTMLElementTagNameMap {
        "webinar-first-component": HTMLWebinarFirstComponentElement;
    }
}
declare namespace LocalJSX {
    interface WebinarFirstComponent {
        "name"?: string;
        "onButtonClicked"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "webinar-first-component": WebinarFirstComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "webinar-first-component": LocalJSX.WebinarFirstComponent & JSXBase.HTMLAttributes<HTMLWebinarFirstComponentElement>;
        }
    }
}
